// const http = require('http');


// const server = http.createServer( (req, res)=>{

//     console.log("Log generated by Index File from Node App");
//     res.write("Welcome to Node App");
//     res.end();

// }  );

// // server.listen(process.env.PORT);
// server.listen(3000);


const express = require("express");
const app = express();

app.get("/", (request, response)=>{
    response.send("Welcome to the Express Demo")
})

app.get("/error", (request, response) => {
    process.exit(1);
})

app.listen(3000)

/*
Environment + Resources
------------
OS (Linux)
NodeJS (Software / CLI)
Open Port (3000)
index.js
package.json

Command Terminal
-------------------
node index.js
*/